name: Deploy Storm dev container to Docker
# Deploys data based off master branch
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .devcontainer-storm/**
jobs:
  Dockerizing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: "${{ secrets.DOCKER_USER }}"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.0.0
      - run: npm install -g @devcontainers/cli
      - run: devcontainer build --workspace-folder ./.devcontainer-storm --image-name $DH_REPO:$GITHUB_SHA

      - name: Docker push Storm dev container
        env:
          DH_REPO: "${{ secrets.DH_REPO }}"
          GITHUB_SHA: "${{ github.sha }}"
        run: |
          docker push $DH_REPO:$GITHUB_SHA
